name: dummy
on:
  push:
    branches:
      - dummy
    paths:
      - 'dummy**'
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, dummy!"
  job2:
    if: github.ref != 'refs/heads/master'
  job3:
    runs-on: ubuntu-latest
    needs: job2
    steps:
      - run: echo "Hello, job3!"
