name: notify GHA annotations
on:
  push

jobs:
  search:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Print gh cli version
        run: gh --version
      - name: Install gh-annotation extension
        run: gh extension install swfz/gh-annotations
      - run: gh annotations --help
      - run: gh annotations --repo $GITHUB_REPOSITORY --json true | jq
