name: Scan container vulnerability
on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v1.5.0
        with:
          dockerfile: ./cvs/web/Dockerfile
