name: Scan container vulnerability
on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v1.5.0
        with:
          dockerfile: ./cvs/web/Dockerfile

      - name: Build an image from Dockerfile
        run: |
          docker build -t docker.io/nemotoy/my-web-app:${{ github.sha }} -f cvs/web/Dockerfile.old .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.0.19
        with:
          image-ref: 'docker.io/nemotoy/my-web-app:${{ github.sha }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: If failure previus steps, print 
        if: ${{ failure() }}
        run: echo "failure"

      - name: Run Dockle image scanner
        uses: hands-lab/dockle-action@v1
        with:
          image: 'docker.io/nemotoy/my-web-app:${{ github.sha }}'
          exit-code: '1'
          exit-level: WARN
  status:
    runs-on: ubuntu-latest
    needs: [build]
    if: always() && (needs.build.result == 'failure')
    steps:
      - name: Print
        run: echo "job failed"